# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aecda5dfce1eba34bd6a47d08dcccda52e9e9e6a4c74ffded67553db2d97a1923d102259f8e266e8628e29a878df19bf7365e8ae9ed245465dc91928c7d8feb

test:
  secret_key_base: 89a4633ba2e8c618da933624f23dabfd1fb331be45d8df5254ff4aed516a545636648ef7611d3bab41be71ed57b760230112267840a93ba5338c57f0ea9a7957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
